### ISSUE TITLE
Oxford CryoStream 800 cooler

### ISSUE THREAD

**Issue by prjemian** [epics-modules/ip#26]
add support for the [Oxford CryoStream 800 cooler](https://www.oxcryo.com/product/cryostream-800)

* [x] #28 - get status from specified controller
* [x] #29 - identify source of status values `0xFFFE` and `0xFFFF`
* [x] #30 - support screens
* [x] #31 - backpressure signal
* [x] #32 - CS800 python simulator

**Comment by prjemian** [comment]
Thanks to David Vine (and James O'Hea for the cs700 that precedes it).

**Comment by prjemian** [comment]
The name pattern for support files in the IP module would change `oxcryo` to `Oxford_CS800` to be consistent.

**Comment by prjemian** [comment]
Leave the simulator as a separate project for now.
